version: '3.8'
services:
  client:
    build:
      dockerfile: dockerfile.dev
    volumes:
      - ./client:/app
      - client-node_modules:/app/node_modules
  api:
    build: 
      dockerfile: dockerfile.dev
    volumes:
      - ./server:/app
      - server-node_modules:/app/node_modules

volumes:
  client-node_modules:
  server-node_modules: